version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: PHONEBOOK_PASSWORD
      POSTGRES_USER: PHONEBOOK_USER
      POSTGRES_DB: PHONEBOOK_DB
    ports:
      - "5433:5432"
