---
name: ci

on:
  push:
    tags:
      - '**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.6"
      - run: go test -v ./... -covermode=atomic -coverprofile=coverage.out
      - uses: codecov/codecov-action@v4
        with:
          files: coverage.out

  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest